### ISSUE TITLE
Clean up extra files?

### ISSUE THREAD

**Issue by mbjoseph** [wino6687/SWEpy#2]
It seems like there are files in this repo that are not needed - can they be deleted?

- `.ipynb_checkpoints/`
- `__pycache__/`
- `.DS_Store`
- `dist/DS_Store`

Maybe others? I'm not as familiar with the conventions for releasing Python libraries. Is it normal to distribute releases by committing .tar.gz files in a `dist/` subdirectory? I guess I would maybe expect this to be available through tagging a release on GitHub, rather than having a .tar.gz file in the repo. But if this is standard, then that's great!

**Comment by wino6687** [comment]
I defintely can clean some of these up. For the python library, I followed [this ](https://packaging.python.org/tutorials/packaging-projects/) guide from pypi for making a pip installable library. 

But i'm sure there are other ways to do it, and if there are cleaner ways to go about it i'm all for it.

I am wondering now if maybe `dist/` subdirectory could be in my .gitignore since it is just for uploading to pypi, and probably not needed in the git? I'll do some digging on that. 

Update: After digging around, I am 99% sure I can remove all the files associated with the pip library from the remote repo and just keep them locally for twine uploads. So I cleaned up all these files and am going to close this issue now!
