### ISSUE TITLE
Getting server down error but can download from web site

### ISSUE THREAD

**Issue by usethedata** [wino6687/SWEpy#7]
I'm attempting to use this package (and sorry about the delay working on the review).  I've successfully gotten it installed, but am not successful in getting it to work.  I've gotten a "server down" error, though I'm able to get a .nc file via the browser from what appears to be the same server if I'm reading the source code correctly (`n5eil01u.ecs.nsidc.org`).  I'm working on a Mac, running High Sierra.  

```
(swepy_env) mac114341:joss-review wb5$ python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from swepy.swepy import swepy
Unable to revert mtime: /Library/Fonts
>>> import datetime
>>> import os
>>> upper_left = [45,45]
>>> lower_right = [40,40]
>>> start = datetime.date(1981,5,5)
>>> end = datetime.date(1982,5,5)
>>> username = "redacted"
>>> password = "alsoredacted"
>>> swe = swepy(path, start, end, upper_left, lower_right, username, password, high_res = True)
Server Down, try again later 
```

But, from my browser, I was able to download `https://n5eil01u.ecs.nsidc.org/MEASURES/NSIDC-0630.001/1978.10.26/NSIDC-0630-EASE2_N12.5km-NIMBUS7_SMMR-1978299-06H-M-SIR-JPL-v1.3.nc` with no issues.

**Comment by wino6687** [comment]
Hi @usethedata, sorry I must not be getting notifications for these issues. I'll get to work on this today. Sorry for the delay!!!

**Comment by wino6687** [comment]
Hi @usethedata, I was able to instantiate the class with your code, however your "path" in the ```swe = swepy(path...)``` is not defined. I am trying to figure out why that is the error you are getting though. 

That error gets thrown by NSIDCdownloader.py when a bad connection (requests connection error) is received but it is not due to a bad EarthData Authentication. The test URL is from the SMAP dataset, though, maybe something I should change. 

Also to note, the automatic scraping is supported from 1992 on due to sensor error in the earlier years. But I think I will add support for those earlier years today since some users may want them. 


After replacing the ```path``` variable with ```os.getcwd()``` I was able to run this code with no server down errors.  Can you give it one more try and then post your ```conda list``` results if it doesn't work still? 

I am running MacOS 10.14.1 Mojave. But also ran this test on linux to verify. 

Thanks!!!

**Comment by wino6687** [comment]
```Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from swepy.swepy import swepy
>>> import datetime
>>> import os 
>>> upper_left = [45,45]
>>> lower_right = [40,40]
>>> start = datetime.date(1981,5,5)
>>> end = datetime.date(1982, 5,5)
>>> username = 'wino6687'
>>> password = 'Desmo12@'
>>> swe = swepy(path, start, end, upper_left, lower_right, username, password, high_res = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'path' is not defined
>>> swe = swepy(os.getcwd(), start, end, upper_left, lower_right, username, password, high_res = True)
>>> 
```
